Repository AY2223S2-CS2103T-F12-1/tp, pull requests merged in 2023-03, with the labels that each got.

#21 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#43 Feat/UserGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#48 Add AddDoctorCommand
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddDoctorCommand.java
  src/main/java/seedu/address/logic/parser/AddDoctorCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Story, priority.High

#49 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#58 Feat/storage v0.2
  build.gradle
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: type.Task, priority.Medium

#59 Fix/storage v0.2
  src/main/java/seedu/address/model/person/Doctor.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Bug, priority.High, severity.High

#80 Enable proper storing, loading and display of doctors
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/DoctorCard.java
  src/main/java/seedu/address/ui/DoctorListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/DoctorListCard.fxml
  src/main/resources/view/DoctorListPanel.fxml
Labels: type.Bug, severity.High

#93 Change example in add-doc command
  src/main/java/seedu/address/logic/commands/AddDoctorCommand.java
Labels: type.Bug

#90 Add tests for edit-doc parser and command
  src/main/java/seedu/address/logic/commands/EditDoctorCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditDoctorCommandTest.java
  src/test/java/seedu/address/logic/parser/EditDoctorCommandParserTest.java
Labels: type.Task

#94 Task/Update PPP
  docs/team/vigonometry.md
Labels: type.Task, priority.Medium

#97 Patient model
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddDoctorCommand.java
  src/main/java/seedu/address/logic/commands/DeleteDoctorCommand.java
  src/main/java/seedu/address/logic/commands/EditDoctorCommand.java
  src/main/java/seedu/address/logic/commands/FindDoctorCommand.java
  src/main/java/seedu/address/logic/parser/AddDoctorCommandParser.java
  src/main/java/seedu/address/logic/parser/FindDoctorCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/doctor/Doctor.java
  src/main/java/seedu/address/model/person/doctor/DoctorContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/doctor/DoctorFilter.java
  src/main/java/seedu/address/model/person/doctor/DoctorStub.java
  src/main/java/seedu/address/model/person/doctor/Specialty.java
  src/main/java/seedu/address/model/person/doctor/UniqueDoctorList.java
  src/main/java/seedu/address/model/person/doctor/Yoe.java
  src/main/java/seedu/address/model/person/patient/Diagnosis.java
  src/main/java/seedu/address/model/person/patient/Height.java
  src/main/java/seedu/address/model/person/patient/Patient.java
  src/main/java/seedu/address/model/person/patient/Remark.java
  src/main/java/seedu/address/model/person/patient/Status.java
  src/main/java/seedu/address/model/person/patient/UniquePatientList.java
  src/main/java/seedu/address/model/person/patient/Weight.java
  src/main/java/seedu/address/storage/JsonAdaptedDoctor.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/DoctorCard.java
  src/main/java/seedu/address/ui/DoctorListPanel.java
  src/main/java/seedu/address/ui/EnlargedContactCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/EditDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/FindDoctorCommandTest.java
  src/test/java/seedu/address/logic/parser/EditDoctorCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindDoctorCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/doctor/DoctorTest.java
  src/test/java/seedu/address/model/person/doctor/SpecialtyTest.java
  src/test/java/seedu/address/model/person/doctor/UniqueDoctorListTest.java
  src/test/java/seedu/address/model/person/doctor/YoeTest.java
  src/test/java/seedu/address/testutil/DoctorBuilder.java
  src/test/java/seedu/address/testutil/EditDoctorDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalDoctors.java
Labels: type.Task, priority.High

#99 Upon filtering doctors through find-doc or list-doc, UI updates the enlarged contact card
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/DoctorListPanel.java
  src/main/java/seedu/address/ui/EnlargedContactCard.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Enhancement, priority.High, severity.Medium

#101 Docedex set up to allow for Patient manipulation
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/doctor/Doctor.java
  src/main/java/seedu/address/model/person/doctor/DoctorStub.java
  src/main/java/seedu/address/model/person/patient/PatientStub.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddDoctorCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelStub.java
  src/test/java/seedu/address/testutil/DoctorBuilder.java
Labels: type.Task, priority.High

#102 Docedex will now store patients assigned to doctors
  src/main/java/seedu/address/model/person/doctor/Doctor.java
  src/main/java/seedu/address/model/person/patient/PatientStub.java
  src/main/java/seedu/address/model/person/patient/Remark.java
  src/main/java/seedu/address/storage/JsonAdaptedDoctor.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/DoctorListPanel.java
Labels: type.Story, priority.High

#103 Tests for Storage Components are complete
  src/main/java/seedu/address/logic/commands/EditDoctorCommand.java
  src/main/java/seedu/address/model/person/doctor/Doctor.java
  src/main/java/seedu/address/model/person/patient/PatientStub.java
  src/main/java/seedu/address/model/person/patient/Status.java
  src/main/java/seedu/address/model/person/patient/Weight.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidDoctorAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidDoctorAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateDoctorAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidDoctorAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalDoctorsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedDoctorTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/DoctorBuilder.java
  src/test/java/seedu/address/testutil/EditDoctorDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/TypicalDoctors.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: type.Task, priority.High

#96 Amend PPP, UG and DG to reflect changes for v1.2
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
  docs/team/praveenkrishna0512.md
Labels: type.Task, priority.Medium

#127 Feat/AddPatientCommand
  .gitignore
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddDoctorCommand.java
  src/main/java/seedu/address/logic/commands/AddPatientCommand.java
  src/main/java/seedu/address/logic/parser/AddDoctorCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
Labels: type.Story, priority.High

#137 Enable storage of unassigned patients
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/doctor/Doctor.java
  src/main/java/seedu/address/storage/JsonAdaptedDoctor.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidDoctorAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidDoctorAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateDoctorAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidDoctorAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalDoctorsAddressBook.json
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalDoctors.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: type.Bug, priority.High, severity.High

#140 Updated Developer Guide to explain implementation of UI interaction
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/UserClickDoctorCardSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/UserClickDoctorCardSequenceDiagram.png
  docs/images/enlarged-contact-card-display.png
Labels: priority.High, severity.VeryLow, type.Docs

#142 Feat/Styling
  src/main/resources/view/ContactDisplay.fxml
  src/main/resources/view/css/LightTheme.css
Labels: type.Enhancement, type.Bug, priority.High, severity.Medium

#141 Feat/DeletePatientCommand
  src/main/java/seedu/address/logic/commands/AddPatientCommand.java
  src/main/java/seedu/address/logic/commands/DeletePatientCommand.java
  src/main/java/seedu/address/logic/parser/AddPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeletePatientCommandParser.java
Labels: type.Story, priority.High

#150 Task/Add Sequence Diagrams
  docs/DeveloperGuide.md
  docs/diagrams/AddDoctorSequenceDiagram.puml
  docs/diagrams/AddPatientSequenceDiagram.puml
  docs/diagrams/DeleteDoctorSequenceDiagram.puml
  docs/diagrams/DeletePatientSequenceDiagram.puml
  docs/images/AddDoctorSequenceDiagram.png
  docs/images/AddPatientSequenceDiagram.png
  docs/images/DeleteDoctorSequenceDiagram.png
  docs/images/DeletePatientSequenceDiagram.png
  docs/templates/DeveloperGuideFeature.md
Labels: priority.Medium, type.Docs

#158 Fix/UserGuide.md
  docs/UserGuide.md
Labels: type.Docs

#157 Enable deletion of references to patients in respective doctors
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/doctor/Doctor.java
  src/test/java/seedu/address/logic/commands/DeletePatientCommandTest.java
  src/test/java/seedu/address/testutil/TypicalDoctors.java
Labels: type.Bug, priority.High, severity.High

#156 Assign and Unassign Patient Command
  src/main/java/seedu/address/logic/commands/AssignPatientCommand.java
  src/main/java/seedu/address/logic/commands/UnassignPatientCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AssignPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UnassignPatientCommandParser.java
Labels: type.Story, priority.High

#163 Fix/Regex for Yoe
  docs/DeveloperGuide.md
  docs/diagrams/AddDoctorSequenceDiagram.puml
  docs/diagrams/AddPatientSequenceDiagram.puml
  docs/images/AddDoctorSequenceDiagram.png
  docs/images/AddPatientSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/AddPatientCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/person/doctor/Yoe.java
Labels: type.Bug, priority.High, severity.Medium

#162 Fix/Sequence Diagrams
  docs/DeveloperGuide.md
  docs/diagrams/AddDoctorSequenceDiagram.puml
  docs/diagrams/AddPatientSequenceDiagram.puml
  docs/images/AddDoctorSequenceDiagram.png
  docs/images/AddPatientSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/AddPatientCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: type.Story, priority.High, type.Docs

#166 Fix buggy display of enlarged information
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/ui/ContactDisplay.java
  src/main/java/seedu/address/ui/DoctorListPanel.java
  src/main/java/seedu/address/ui/EnlargedDoctorInfoCard.java
  src/main/java/seedu/address/ui/EnlargedInfoCardDisplayController.java
  src/main/java/seedu/address/ui/EnlargedPatientInfoCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PatientListPanel.java
Labels: priority.Medium, severity.Medium

#170 Enable proper loading of multiple patients and display of selection queries
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AssignPatientCommand.java
  src/main/java/seedu/address/model/person/doctor/Doctor.java
  src/main/java/seedu/address/model/person/doctor/DoctorFilter.java
  src/main/java/seedu/address/model/person/patient/Patient.java
  src/main/java/seedu/address/model/person/patient/PatientFilter.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/ContactDisplay.java
  src/main/java/seedu/address/ui/DoctorListPanel.java
  src/main/java/seedu/address/ui/EnlargedInfoCardDisplayController.java
  src/main/java/seedu/address/ui/PatientListPanel.java
Labels: priority.Medium

#171 Amend edit-doc and edit-ptn to update sister lists
  src/main/java/seedu/address/logic/commands/EditDoctorCommand.java
  src/main/java/seedu/address/logic/commands/EditPatientCommand.java
  src/main/java/seedu/address/model/person/doctor/Doctor.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPatientCommandTest.java
  src/test/java/seedu/address/testutil/DoctorBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/TypicalDoctors.java
Labels: priority.High

#173 Fix/Add ptn
  src/main/java/seedu/address/logic/commands/AddPatientCommand.java
  src/main/java/seedu/address/logic/parser/AddPatientCommandParser.java
Labels: type.Bug, priority.High, severity.High

#175 Add prefix usage for assign and unassign patient, Fix unassign patient command
  src/main/java/seedu/address/logic/commands/AssignPatientCommand.java
  src/main/java/seedu/address/logic/commands/UnassignPatientCommand.java
  src/main/java/seedu/address/logic/parser/AssignPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/UnassignPatientCommandParser.java
Labels: type.Bug, priority.High, severity.High

#177 GUI is responsive to Select Doc Command
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/SelectDoctorCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SelectDoctorCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/doctor/UniqueDoctorList.java
  src/main/java/seedu/address/ui/ContactDisplay.java
  src/main/java/seedu/address/ui/EnlargedInfoCardDisplayController.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High

#179 Fix/Styling Issues
  docs/UserGuide.md
  docs/images/AssignPtn.png
  docs/images/FindDoc.png
  docs/images/FindPtn.png
  docs/images/ListDoc.png
  docs/images/ListPtn.png
  docs/images/Unassign.png
Labels: priority.Medium, type.Docs

#181 Docs/Fix Images
  docs/UserGuide.md
  docs/index.md
Labels: priority.High, type.Docs

#182 Clear previous selection upon selection command
  src/main/java/seedu/address/logic/commands/AssignPatientCommand.java
  src/main/java/seedu/address/logic/commands/UnassignPatientCommand.java
  src/main/java/seedu/address/ui/ContactDisplay.java
  src/main/java/seedu/address/ui/DoctorListPanel.java
  src/main/java/seedu/address/ui/PatientListPanel.java
Labels: priority.High

#183 Remove commands in addressBookParser and test cases
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High

#184 Made cosmetic changes
  src/main/java/seedu/address/logic/commands/AddDoctorCommand.java
  src/main/java/seedu/address/logic/commands/AddPatientCommand.java
  src/main/java/seedu/address/logic/commands/EditDoctorCommand.java
  src/main/java/seedu/address/logic/commands/EditPatientCommand.java
  src/main/java/seedu/address/ui/ContactDisplay.java
  src/main/java/seedu/address/ui/DoctorCard.java
  src/main/java/seedu/address/ui/EnlargedDoctorInfoCard.java
  src/main/java/seedu/address/ui/EnlargedPatientInfoCard.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/resources/view/DoctorListCard.fxml
  src/main/resources/view/EnlargedDoctorInfoCard.fxml
  src/main/resources/view/EnlargedPatientInfoCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PatientListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/css/DarkTheme.css
  src/main/resources/view/css/LightTheme.css
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditDoctorCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPatientCommandTest.java
Labels: priority.High

#186 Add command summary section
  docs/UserGuide.md
Labels: type.Docs

#188 Docs/UserGuide reformatting
  docs/UserGuide.md
Labels: priority.Medium, type.Docs

#189 Docs/Formatting Fixes
  docs/UserGuide.md
Labels: priority.High, severity.High, type.Docs
